name: Build

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/saizaax/yasa-frontend
  SERVICE_NAME: yasa_nginx
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log in to registry
        run: echo "$GH_PAT" | docker login $REGISTRY -u $GITHUB_ACTOR --password-stdin

      - name: Push image
        run: |
          docker tag $IMAGE_NAME $IMAGE_NAME:latest
          docker tag $IMAGE_NAME $IMAGE_NAME:$GITHUB_RUN_NUMBER
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$GITHUB_RUN_NUMBER

  update-service:
    needs: [build-and-push]
    runs-on: ubuntu-latest
    steps:
      - name: Update Docker service
        uses: appleboy/ssh-action@master
        env:
          IMAGE: ${{ env.IMAGE_NAME }}:${{ github.run_number }}
          SERVICE: ${{ env.SERVICE_NAME }}
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          envs: IMAGE,SERVICE
          script: docker service update --image $IMAGE $SERVICE --with-registry-auth